/*
SQLyog Professional v12.08 (64 bit)
MySQL - 5.7.26 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

create table `go_product` (
	`p_id` int (11),
	`p_name` varchar (2295),
	`p_img1` varchar (2295),
	`p_img2` varchar (2295),
	`p_img3` varchar (2295),
	`p_img4` varchar (2295),
	`p_img5` varchar (2295),
	`p_img6` varchar (2295),
	`p_img7` varchar (2295),
	`p_img8` varchar (2295),
	`p_type` varchar (450),
	`p_price1` varchar (450),
	`p_price2` varchar (450),
	`p_present` varchar (4500),
	`p_stock` varchar (450),
	`p_version1` varchar (450),
	`p_version2` varchar (450),
	`p_color1` varchar (450),
	`p_color2` varchar (450)
); 
insert into `go_product` (`p_id`, `p_name`, `p_img1`, `p_img2`, `p_img3`, `p_img4`, `p_img5`, `p_img6`, `p_img7`, `p_img8`, `p_type`, `p_price1`, `p_price2`, `p_present`, `p_stock`, `p_version1`, `p_version2`, `p_color1`, `p_color2`) values('1','MacBookpro','MacBookPro.jpg','MacBookPro.jpg','MacBookPro.jpg','MacBookPro.jpg','MacBookPro.jpg','MacBookPro.jpg','MacBookPro.jpg','MacBookPro.jpg','ad-product-computer','18999','21935','Apple MacBook Air【教育优惠】13.3 8核M1芯片(7核图形处理器) 8G 256G SSD 银色 笔记本电脑 MGN93CH/A','100','13.3英寸M1芯片8+7核8G+256G','13.3英寸M1芯片8+7核16G+2T','深空黑色','银色');
insert into `go_product` (`p_id`, `p_name`, `p_img1`, `p_img2`, `p_img3`, `p_img4`, `p_img5`, `p_img6`, `p_img7`, `p_img8`, `p_type`, `p_price1`, `p_price2`, `p_present`, `p_stock`, `p_version1`, `p_version2`, `p_color1`, `p_color2`) values('2','MagicBookpro','MagicBookpro.png','MagicBookpro.png','MagicBookpro.png','MagicBookpro.png','MagicBookpro.png','MagicBookpro.png','MagicBookpro.png','MagicBookpro.png','ad-product-computer','5499','6199','16.1英寸高清全面屏，100%色域值,窄边框轻薄机身,全新第八代酷睿处理器，高性能体验，14小时长续航','100','i5 8GB 512GB独显','i5 8GB 512GB','星空灰','冰河银');
insert into `go_product` (`p_id`, `p_name`, `p_img1`, `p_img2`, `p_img3`, `p_img4`, `p_img5`, `p_img6`, `p_img7`, `p_img8`, `p_type`, `p_price1`, `p_price2`, `p_present`, `p_stock`, `p_version1`, `p_version2`, `p_color1`, `p_color2`) values('3','RedmiBook 14增强版','RedmiBook14.png','RedmiBook 14.png','RedmiBook 14.png','RedmiBook 14.png','RedmiBook 14.png','RedmiBook 14.png','RedmiBook 14.png','RedmiBook 14.png','ad-product-computer','4199','3999','全新十代酷睿处理器MX250独显/14英寸超窄边框高清屏/小米手环极速解锁炫酷多彩任你挑选','100','i5 8G 512G MX250','i5 8G 256G MX250','深空灰','月光银');
insert into `go_product` (`p_id`, `p_name`, `p_img1`, `p_img2`, `p_img3`, `p_img4`, `p_img5`, `p_img6`, `p_img7`, `p_img8`, `p_type`, `p_price1`, `p_price2`, `p_present`, `p_stock`, `p_version1`, `p_version2`, `p_color1`, `p_color2`) values('4','小米游戏本2019款','xiaomigamebok.jpg','xiaomigamebok.jpg','xiaomigamebok.jpg','xiaomigamebok.jpg','xiaomigamebok.jpg','xiaomigamebok.jpg','xiaomigamebok.jpg','xiaomigamebok.jpg','ad-product-computer','8999','8599','九代酷睿标压处理器/144Hz刷新率/3＋2包围式热管/12V台机级别散热风扇/72%色域','100','i7 16G 1T PCle','i7 16G 512GB PCle','暗夜灰','若雪粉');
insert into `go_product` (`p_id`, `p_name`, `p_img1`, `p_img2`, `p_img3`, `p_img4`, `p_img5`, `p_img6`, `p_img7`, `p_img8`, `p_type`, `p_price1`, `p_price2`, `p_present`, `p_stock`, `p_version1`, `p_version2`, `p_color1`, `p_color2`) values('5','HUAWEIMate30Pro 5G','huaweimate30pro5g_black.jpg','huaweimate30pro5g_black.jpg','huaweimate30pro5g_black.jpg','huaweimate30pro5g_black.jpg','huaweimate30pro5g_black.jpg','huaweimate30pro5g_black.jpg','huaweimate30pro5g_black.jpg','huaweimate30pro5g_black.jpg','ad-product-phone','6999','7899','全网通8GB + 256GB鹿麟990 5G旗舰SoC芯片，支持双模SA/NSA ;超感光徕卡电影四摄;超曲面OLED 环幕屏;4OW','100','6GB+256GB','8GB+512GB','亮黑色','翡冷翠');
insert into `go_product` (`p_id`, `p_name`, `p_img1`, `p_img2`, `p_img3`, `p_img4`, `p_img5`, `p_img6`, `p_img7`, `p_img8`, `p_type`, `p_price1`, `p_price2`, `p_present`, `p_stock`, `p_version1`, `p_version2`, `p_color1`, `p_color2`) values('6','HUAWEI P30 5G','huaweip30pro_black.jpg','huaweip30pro_black.jpg','huaweip30pro_black.jpg','huaweip30pro_black.jpg','huaweip30pro_black.jpg','huaweip30pro_black.jpg','huaweip30pro_black.jpg','huaweip30pro_black.jpg','ad-product-phone','4988','5488','麒麟980超感光徕卡四摄屏内指纹双景录像华为P30Pro尊享金卡专属服务权益','100','8GB+128GB','8GB+256GB','亮黑色','天空之境');
insert into `go_product` (`p_id`, `p_name`, `p_img1`, `p_img2`, `p_img3`, `p_img4`, `p_img5`, `p_img6`, `p_img7`, `p_img8`, `p_type`, `p_price1`, `p_price2`, `p_present`, `p_stock`, `p_version1`, `p_version2`, `p_color1`, `p_color2`) values('7','小米9 Pro 5G','xiaomicc9pro5G_black.jpg','xiaomicc9pro5G_black.jpg','xiaomicc9pro5G_black.jpg','xiaomicc9pro5G_black.jpg','xiaomicc9pro5G_black.jpg','xiaomicc9pro5G_black.jpg','xiaomicc9pro5G_black.jpg','xiaomicc9pro5G_black.jpg','ad-product-phone','3699','4299','5G双卡全网通超高速网络/骁龙855Plus旗舰处理器40W有线闪充＋30W无线闪充＋10W无线反充，4000mAh长续航/4800万全焦段三摄','100','8GB+128GB','8GB+512GB','钛银黑','梦之白');
insert into `go_product` (`p_id`, `p_name`, `p_img1`, `p_img2`, `p_img3`, `p_img4`, `p_img5`, `p_img6`, `p_img7`, `p_img8`, `p_type`, `p_price1`, `p_price2`, `p_present`, `p_stock`, `p_version1`, `p_version2`, `p_color1`, `p_color2`) values('8','小米 CC9 Pro','xiaomicc9pro_black.jpg','xiaomicc9pro_black.jpg','xiaomicc9pro_black.jpg','xiaomicc9pro_black.jpg','xiaomicc9pro_black.jpg','xiaomicc9pro_black.jpg','xiaomicc9pro_black.jpg','xiaomicc9pro_black.jpg','ad-product-phone','2799','3099','1亿像素主摄/全场景五摄像头/四闪光灯/3200万自拍/10倍混合光学变焦，50 倍数字变焦5260mAh电量/标配30W疾速快充','100','8GB+128GB','8GB+128GB','暗夜魅影','魔法绿境');
insert into `go_product` (`p_id`, `p_name`, `p_img1`, `p_img2`, `p_img3`, `p_img4`, `p_img5`, `p_img6`, `p_img7`, `p_img8`, `p_type`, `p_price1`, `p_price2`, `p_present`, `p_stock`, `p_version1`, `p_version2`, `p_color1`, `p_color2`) values('9','华为平板M6高能版8.4英寸','HUAWEIM6_blue.jpg','HUAWEIM6_blue.jpg','HUAWEIM6_blue.jpg','HUAWEIM6_blue.jpg','HUAWEIM6_blue.jpg','HUAWEIM6_blue.jpg','HUAWEIM6_blue.jpg','HUAWEIM6_blue.jpg','ad-product-pad','2699','2799','麒麟980芯片2K超清画质哈曼卡顿调音液冷散热 GPUTurbo加速游戏体验','100','6GB+128GB WiFi','6GB+128GB 全网通','幻影蓝','幻影红');
insert into `go_product` (`p_id`, `p_name`, `p_img1`, `p_img2`, `p_img3`, `p_img4`, `p_img5`, `p_img6`, `p_img7`, `p_img8`, `p_type`, `p_price1`, `p_price2`, `p_present`, `p_stock`, `p_version1`, `p_version2`, `p_color1`, `p_color2`) values('10','华为平板M5青春版8.0英寸','HUAWEIM5_golden.png','HUAWEIM5_golden.png','HUAWEIM5_golden.png','HUAWEIM5_golden.png','HUAWEIM5_golden.png','HUAWEIM5_golden.png','HUAWEIM5_golden.png','HUAWEIM5_golden.png','ad-product-pad','1899','1599','智能声控平板哈曼卡顿调音麒麟710芯片AI智慧语音控制一切好说、哈曼卡顿调音细腻鲜活、麒麟710芯片强大内芯、5100毫安大电池持久续航','100','4GB+128GB','4GB+128GB','白色','黑色');
insert into `go_product` (`p_id`, `p_name`, `p_img1`, `p_img2`, `p_img3`, `p_img4`, `p_img5`, `p_img6`, `p_img7`, `p_img8`, `p_type`, `p_price1`, `p_price2`, `p_present`, `p_stock`, `p_version1`, `p_version2`, `p_color1`, `p_color2`) values('11','华为平板 M6 10.8英寸麒麟980芯片','HUAWEIM510_golden.png','HUAWEIM510_golden.png','HUAWEIM510_golden.png','HUAWEIM510_golden.png','HUAWEIM510_golden.png','HUAWEIM510_golden.png','HUAWEIM510_golden.png','HUAWEIM510_golden.png','ad-product-pad','2699','3999','2K高清屏应用分屏一屏两用哈曼卡顿调音四声道四扬声器','100','4GB+64GB','6GB+256GB','黑色','白色');
insert into `go_product` (`p_id`, `p_name`, `p_img1`, `p_img2`, `p_img3`, `p_img4`, `p_img5`, `p_img6`, `p_img7`, `p_img8`, `p_type`, `p_price1`, `p_price2`, `p_present`, `p_stock`, `p_version1`, `p_version2`, `p_color1`, `p_color2`) values('12','小米平板48/ 10.1英寸','mi_black.png','mi_black.png','mi_black.png','mi_black.png','mi_black.png','mi_black.png','mi_black.png','mi_black.png','ad-product-pad','1499','1899','大电量,超长续航/支持Al人脸识别/后置1300万，前置500万摄像头/金属机身，超窄边框/骁龙660八核处理器','100','10英寸LTE版 64GB','10英寸LTE版','黑色','粉色');
insert into `go_product` (`p_id`, `p_name`, `p_img1`, `p_img2`, `p_img3`, `p_img4`, `p_img5`, `p_img6`, `p_img7`, `p_img8`, `p_type`, `p_price1`, `p_price2`, `p_present`, `p_stock`, `p_version1`, `p_version2`, `p_color1`, `p_color2`) values('13','AirPodsPro','AirPodsPro_black.jpg','AirPodsPro_black.jpg','AirPodsPro_black.jpg','AirPodsPro_black.jpg','AirPodsPro_black.jpg','AirPodsPro_black.jpg','AirPodsPro_black.jpg','AirPodsPro_black.jpg','ad-product-ear','1999','2100','主动降噪Ⅰ通透模式Ⅰ全新设计Ⅰ卓越音质','100','IPX5','IPX6','白色','黑色');
insert into `go_product` (`p_id`, `p_name`, `p_img1`, `p_img2`, `p_img3`, `p_img4`, `p_img5`, `p_img6`, `p_img7`, `p_img8`, `p_type`, `p_price1`, `p_price2`, `p_present`, `p_stock`, `p_version1`, `p_version2`, `p_color1`, `p_color2`) values('14','vivoTWSEarphone真无线蓝牙耳机','vivoTWSEarphone_blue.jpg','vivoTWSEarphone_blue.jpg','vivoTWSEarphone_blue.jpg','vivoTWSEarphone_blue.jpg','vivoTWSEarphone_blue.jpg','vivoTWSEarphone_blue.jpg','vivoTWSEarphone_blue.jpg','vivoTWSEarphone_blue.jpg','ad-product-ear','999','1200','疾速体验l智慧连接l高清音质Ⅰ语音声控l无感佩戴(温馨提示:拆封包装后不支持无理由退货)','100','3.5mm','Type-c','星际蓝','皓月白');
insert into `go_product` (`p_id`, `p_name`, `p_img1`, `p_img2`, `p_img3`, `p_img4`, `p_img5`, `p_img6`, `p_img7`, `p_img8`, `p_type`, `p_price1`, `p_price2`, `p_present`, `p_stock`, `p_version1`, `p_version2`, `p_color1`, `p_color2`) values('15','小米蓝牙耳机青春版','mmi6_white.jpg','mmi6_white.jpg','mmi6_white.jpg','mmi6_white.jpg','mmi6_white.jpg','mmi6_white.jpg','mmi6_white.jpg','mmi6_white.jpg','ad-product-ear','59','108','6.5克轻巧/蓝牙4.1高清通话音质/支持切歌、音量调节','100','标准','豪华','黑色','白色');
insert into `go_product` (`p_id`, `p_name`, `p_img1`, `p_img2`, `p_img3`, `p_img4`, `p_img5`, `p_img6`, `p_img7`, `p_img8`, `p_type`, `p_price1`, `p_price2`, `p_present`, `p_stock`, `p_version1`, `p_version2`, `p_color1`, `p_color2`) values('16','HUAWEIFreeBuds 3 无线耳机','HUAWEIFreeBuds_gray.jpg','HUAWEIFreeBuds_gray.jpg','HUAWEIFreeBuds_gray.jpg','HUAWEIFreeBuds_gray.jpg','HUAWEIFreeBuds_gray.jpg','HUAWEIFreeBuds_gray.jpg','HUAWEIFreeBuds_gray.jpg','HUAWEIFreeBuds_gray.jpg','ad-product-ear','2000','2100','半开放式主动降噪，麒麟Al芯片，抗干扰，低时延，无线快充，佩戴稳固舒适，震撼低音，搭配Mate30系列体验更佳','100','动圈式','圈铁混合','陶瓷白','碳晶黑');
